debian/tests/setup-apt-dir, setup-apt-dir.sh: Add an option to enable i386 arch.

diff --git a/debian/tests/setup-apt-dir b/debian/tests/setup-apt-dir
--- a/debian/tests/setup-apt-dir
+++ b/debian/tests/setup-apt-dir
@@ -43,4 +43,18 @@ else
     exit 1
 fi
 
+setup-apt-dir.sh -c focal -m http://archive.ubuntu.com/ubuntu --i386 -o aptdir.log
+if [ ! -e aptdir.log ]; then
+    echo "aptdir.log doesn't exist."
+    exit 1
+fi
+APTDIR="$(cat aptdir.log)"
+if [ -n "$APTDIR" ] && [ -d "$APTDIR" ] && [[ "$APTDIR" =~ ^/tmp/apt\. ]]; then
+    apt-cache -o "Dir=$APTDIR" -o "Dir::State::status=$APTDIR/var/lib/dpkg/status" policy libc6:i386 | grep libc6:i386
+    rm -fr "$APTDIR" aptdir.log
+else
+    echo "APTDIR = '$APTDIR' invalid."
+    exit 1
+fi
+
 exit 0
